# Use the official Microsoft ASP.NET Core runtime base image
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app

# Declare the build-time argument
ARG DEPLOY_DATE

# Map it to an environment variable so it persists in the image
ENV DEPLOY_DATE=$DEPLOY_DATE

# Copy all the pre-published files from the local directory into the container
COPY . .

# Expose a custom container port, since the standard .NET is likely used by other apps
EXPOSE 55551

# Configure the container to execute your Web API DLL on startup
ENTRYPOINT ["dotnet", "PilotApi.Web.dll"]
