<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Library</OutputType>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\PilotApi.Domain\PilotApi.Domain.csproj" />
	<ProjectReference Include="..\PilotApi.Repositories\PilotApi.Repositories.csproj" />
	<ProjectReference Include="..\PilotApi.Shared\PilotApi.Shared.csproj" />
  </ItemGroup>

</Project>
