<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Library</OutputType>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Dapper" />
	<PackageReference Include="Microsoft.Data.SqlClient" />
	<PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\PilotApi.Domain\PilotApi.Domain.csproj" />
	<ProjectReference Include="..\PilotApi.Shared\PilotApi.Shared.csproj" />
  </ItemGroup>

</Project>
